import Head from "next/head";
import Script from "next/script";
import dynamic from "next/dynamic";

const LazyContent = dynamic(() => import("../../components/Remote/Content"), {
  ssr: false,
});

export default function Home() {
  return (
    <div style={{ width: "100%", height: "100%" }}>
      <Head>
        <title>Remote Control</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="../node_modules/socket.io/client-dist/socket.io.js"></Script>
      </Head>

      <main
        style={{
          width: "100%",
          height: "100%",
        }}
      >
        <LazyContent />
      </main>
    </div>
  );
}
